#pragma once

class BotWorkflow {
public:
    enum class WorkflowMessage {
        STEP_SELECT_LANGUAGE,
        STEP_SELECT_THEME_MESSAGE,
        STEP_SELECT_SIZE,
        STEP_SELECT_ANTIMOSAIC_MODE,
        STEP_ADD_ANTIMOSAIC_PHOTO,
        STEP_ADD_PHOTO_MESSAGE,
        STEP_WAITING_FOR_RESULT_MESSAGE,
        STEP_FINISHED_MESSAGE,
        STEP_FINISHED,
        STEP_DISABLED,
        CAPTION_ANTI_MOSAIC,
        CAPTION_ANTI_MOSAIC_ORIGINAL_PIC,
        CAPTION_ANTI_MOSAIC_ANOTHER_PIC,
        ERROR_PHOTO_NOT_UPLOADED,
        ERROR_PHOTO_PROCESSING_FAILED
    };

    enum class RequestStep {
        REQUEST_STEP_WAITING,
        REQUEST_STEP_IN_PROGRESS,
        REQUEST_STEP_ERROR_UPDATING_STEP,
        REQUEST_STEP_ERROR_EXECUTING_METAPIXEL_COMMAND,
        REQUEST_STEP_ERROR_FAILED_TO_GET_USER_ID,
        REQUEST_STEP_ERROR_ADDING_CAPTION,
        REQUEST_STEP_FINISHED
    };
};