#pragma once

class BotWorkflow {
public:
    enum class WorkflowMessage {
        STEP_SELECT_LANGUAGE,
        STEP_SELECT_THEME_MESSAGE,
        STEP_SELECT_SIZE,
        STEP_SELECT_ANTIMOSAIC_MODE,
        STEP_ADD_ANTIMOSAIC_PHOTO,
        STEP_ADD_PHOTO_MESSAGE,
        STEP_WAITING_FOR_RESULT_MESSAGE,
        STEP_FINISHED_MESSAGE,
        STEP_FINISHED,
        CAPTION_ANTI_MOSAIC,
        CAPTION_ANTI_MOSAIC_ORIGINAL_PIC,
        CAPTION_ANTI_MOSAIC_ANOTHER_PIC,
        ERROR_PHOTO_NOT_UPLOADED,
        ERROR_PHOTO_PROCESSING_FAILED
    };
};